services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8081:8081"
    networks:
      - nifi-net
    environment:
      - NIFI_WEB_HTTP_PORT=8080


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    networks:
      - es-net
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk-net
    depends_on:
      - elasticsearch
  
  redpanda:
    image: vectorized/redpanda:v21.11.0
    ports:
      - "9092:9092"
    environment:
      - REDPANDA_BROKER_ID=0
      - REDPANDA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092


networks:
  nifi-net:
    driver: bridge
  es-net:
    driver: bridge
